### DISCUSSION TITLE
How to change default font?

### DISCUSSION THREAD

**Discussion by dontdieych** [Heroor/md-reader#83] [Q&A]
Change 'sans-serif' to other fonts does nothing on custom css editor.

**Comment by Heroor** [comment]
The following selectors can be tried. They take effect after I test them:

```css
#mdr__root {
  --font-family: 'YOUR_FONT';
}
```

The target font needs to have been installed in your computer.
